fix(workflows): Add debug section to workflow to better understand issues

diff --git a/.github/workflows/release_tag.yml b/.github/workflows/release_tag.yml
--- a/.github/workflows/release_tag.yml
+++ b/.github/workflows/release_tag.yml
@@ -27,13 +27,22 @@ jobs:
       - name: Setup | Force correct release branch on workflow sha
         run: |
           git checkout -B ${{ github.ref_name }} ${{ github.sha }}
+          
+
+      - name: Debug | Verify File Paths
+        run: |
+          echo "Current Directory: $(pwd)"
+          ls -la
+          cat pyproject.toml
+          test -f CHANGELOG.md && echo "CHANGELOG.md exists" || echo "CHANGELOG.md missing"
+
 
       - name: Action | Semantic Version Release
         id: release
         # Adjust tag with desired version if applicable.
         uses: python-semantic-release/python-semantic-release@v9.12.0
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          github_token: ${{ secrets.GH_TOKEN }}
           git_committer_name: "github-actions"
           git_committer_email: "actions@users.noreply.github.com"
 
@@ -42,5 +51,5 @@ jobs:
         uses: python-semantic-release/publish-action@v9.8.9
         if: steps.release.outputs.released == 'true'
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          github_token: ${{ secrets.GH_TOKEN }}
           tag: ${{ steps.release.outputs.tag }}
